### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by DiogenesBR** [simoninithomas/awesome-ai-tools-for-game-dev#2]
## Image Generation

-  **Leonardo AI** (Proprietary, Sign Up, Paid, Free Limited daily generations) 
    https://app.leonardo.ai/
    
-   **ControlNet** (Open Source, Apache 2, Free)
     Let's put your character, in the correct position.
     https://github.com/lllyasviel/ControlNet-v1-1-nightly 

     Don't know how to draw that animated sprite? I got you covered (never tried myself my potato don't run SD)
     https://www.youtube.com/watch?v=Ffl8b_GfJ-M&list=PLxBP8DoRCb7ZI3fuJOJ2LNS5TinfhQW9W&index=1

## AI NPC

-   **Inworld** (Proprietary, Sign Up, Paid, Free Limited daily Interactions) 
    Create a personality for your NPCs
    https://inworld.ai
    https://inworld.ai/arcade (cool place to see the characters other people made)

## Python Libraries 

-    **NeMo Guardrails** (Open Source, Apache 2, Free)
     Limit what a NPC could talk about
     https://github.com/NVIDIA/NeMo-Guardrails 

-    **Guidance** (Open Source, MIT, Free)
     A library to help your LLM to understand your prompts
     https://github.com/microsoft/guidance

## C# Libraries

-   **Python.Net** (Open Source, MIT)
    Integrate Python libraries with .Net and .Net Libraries with Python
    https://github.com/pythonnet/pythonnet

-   **Hugging Face API Unity Integration** (Open Source, Apache 2, Free) 
    Integration for the Hugging Face Inference API and Unity
     https://github.com/huggingface/unity-api

## Story Telling Models
Want to make that crazy lore for your world with a lot of text?

-    **MPT-7B-StoryWriter-65k+** (Open Source, Apache-2.0, Free)
     https://huggingface.co/mosaicml/mpt-7b-storywriter

-    **Claude 100k** (Proprietary, Paid, API access, Waitlisted)
      https://huggingface.co/mosaicml/mpt-7b-storywriter

-    **GTP-4 32k** (Proprietary, Paid, API access, Waitlisted)
      https://platform.openai.com/docs/models/overview

**Comment by simoninithomas** [comment]
Ok no problem I'm making it. Thanks for you suggestions 🤗

**Comment by simoninithomas** [comment]
✅
